### PR TITLE
Latest comrak (0.2.2)

### PR DESCRIPTION
**Pull request by kivikakk**
This fixes some security vulnerabilities and makes things a bit faster! From [the changelog](https://github.com/kivikakk/comrak/blob/0.2.2/changelog.txt):

```
### 0.2.2

* Fix for pathological reference link parsing.

### 0.2.1

* Speed optimisations.

### 0.2.0

* The formatters no longer produce Strings themeselves; you must specify an
  output stream.
* Speed up whitespace normalisation.

### 0.1.9

* Multibyte character fix for autolink (#35, Shaquille Johnson).
* Resolve panics with tables in awkward situations (#36).

### 0.1.8

* Fix possible DoS in link parsing (#33, Demi Obenour).
```

### CODE REVIEW

**Comment by kivikakk** [comment]
```
W: The repository 'http://ppa.launchpad.net/kalakris/cmake/ubuntu trusty Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/kalakris/cmake/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/kalakris/cmake/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

kalakris' cmake PPA disappeared? :O

**Comment by kivikakk** [comment]
Oh wait, just not on trusty. Hrm.

**Comment by kivikakk** [comment]
Bundled in the fix to `.travis.yml` here too.

**Comment by onur** [comment]
Comrak is great, thanks! I am also glad crates.io is using it.

**Pull request merged**
