### PR TITLE
Update cargo to latest revision

### PR DESCRIPTION
**Pull request by onur**
I believe this patch is ready, but needs to be properly tested.

Fixes: #65

### CODE REVIEW

**Comment by bluss** [comment]
I don't know if it's the news you want to get, but no new releases have been rendered since this was merged.

**Comment by onur** [comment]
Yes @bluss, this update also fixed #46.

docs.rs is building missing `google-*` crates right now and its taking a while.

**Comment by bluss** [comment]
Aha, so we are stuck in the backlog, that's fine. Would it be an idea to mark crates as being equivalent in all arches? It seems like a waste and I'd do it if it leads to faster publishing. I mean, it's a very useful thing when it matters, but often it doesn't.

**Comment by onur** [comment]
I am not sure if it is possible to detect arch-specific documentation differences before building a crate.

**Pull request merged**
